### PR TITLE
Sync with production

### PR DESCRIPTION
**Pull request by bjsowa**

### CODE REVIEW

**Review by Krzemien97 — DISMISSED** [review]
@bjsowa ready to merge
LGTM

**Review by Krzemien97 — DISMISSED** [review]

**Review by bjsowa — COMMENTED** [review]
@Krzemien97 Could you add `description` metadata to each doc?

**Comment by bjsowa** [comment]
@Krzemien97 Shouldn't `Charging station assembly manual` be part of `Assembly manual` instead of `Documentation`

**Comment by bjsowa** [comment]
`Install ROS on a bootable USB drive` should be archived. The last image we generated is for ROS melodic and we don't support this anymore

**Comment by Krzemien97** [comment]
> @Krzemien97 Could you add `description` metadata to each doc?

Yes, I will do that.

---

> @Krzemien97 Shouldn't `Charging station assembly manual` be part of `Assembly manual` instead of `Documentation`

Currently it mirrors documentation structure from our old docs. I will change that in the future (when we will reorganize whole docs structure).

**Review by Krzemien97 — APPROVED** [review]

**Review by szlachcic — APPROVED** [review]

**Pull request merged**
