### PR TITLE
Sync with production

### PR DESCRIPTION
**Pull request by Krzemien97**
- Add `FusionEmbed` component
- Allow `LinkButton` to get doc info from sidebar
- Add `ProductPreview` component
- `ImageZoom` and `LinkButton` components are now imported into mdx files by default

### CODE REVIEW

**Review by Krzemien97 — COMMENTED** [review]
Its required for docs to have proper `Last updated` field. Currently all pages have date from last PR.

**Comment by bjsowa** [comment]
> Its required for docs to have proper `Last updated` field. Currently all pages have date from last PR.

Because all pages were modified by last PR. I don't see a problem

**Comment by Krzemien97** [comment]
Oh, I forgot about descriptions. Still, according to [Docusaurus docs](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#showLastUpdateTime:~:text=Whether%20to%20display%20the%20last%20date%20the%20doc%20was%20updated.%20This%20requires%20access%20to%20git%20history%20during%20the%20build%2C%20so%20will%20not%20work%20correctly%20with%20shallow%20clones%20(a%20common%20default%20for%20CI%20systems).%20With%20GitHub%20actions/checkout%2C%20usefetch%2Ddepth%3A%200.) it is required to have proper dates.

**Comment by bjsowa** [comment]
Why are we making a shallow clone then? Is it to speed up CI?

**Comment by Krzemien97** [comment]
It works the other way around - `fetch-depth: 0` means deep clone - [source](https://github.com/actions/checkout#:~:text=Set%20fetch%2Ddepth%3A%200%20to%20fetch%20all%20history%20for%20all%20branches%20and%20tags.).

**Review by bjsowa — APPROVED** [review]

**Review by szlachcic — APPROVED** [review]

**Pull request merged**
